### ISSUE TITLE
Question about a suitable receiver 

### ISSUE THREAD

**Issue by joelhauxwell** [GDWoody/Pixel-Controllers#1]
Hello,

I have been 'upgrading' my addressable LED strips to work with differential signals and your bbb_all_diff looks ideal for the transmit end.

My design for the receive end is using the SN75176AP IC.... do you have any idea if this will work with the AM26C31 you have used for the transmitter?

This is what I have done for the start of every strip:

![image](https://user-images.githubusercontent.com/71120697/231413942-b5aaec99-85db-4e59-be58-0e6c1dcc5d40.png)

If not, it would be great if I could find something pin compatible for my RX.

Cheers,

Joel.

**Comment by GDWoody** [comment]
Hi Joel,

I don't know if a SN75176AP will work with an AM26C31, however, if you let me know a bit more about your project like what controller, how many outputs etc I might be able to come up with a solution for you.

**Comment by joelhauxwell** [comment]
Hi,

Thanks for getting back to me.

Ideally, I just need to come up with a compatible single channel receiver for your bbb_all_diff controller.  I would like to make it fit within the same physical size as the PCB I had already made if possible.

I have a load of WS2812B strips mounted in aluminium extrusion and preparing for Christmas 2023! - differential wiring will make it so much easier to hook up.

If you could recommend a suitable receiver for the AM26C31 that would be great - even better if there is a something single channel (and small!).

**Comment by GDWoody** [comment]
Joel,

Sure, what are the dimensions of your board?

**Comment by joelhauxwell** [comment]
Here is the board:

![image](https://user-images.githubusercontent.com/71120697/231495785-61cf07ab-08de-4b16-b651-3ef27242717d.png)

If I can keep the mounting holes in the same place that would be advantageous.

Im happy to switch out to SMD components to save some space....

**Comment by GDWoody** [comment]
Hi,

Could something like this work for you?


ESP32 WT32-ETH01 WLED Controller with 4 SN75176AP Transceivers.

**Comment by joelhauxwell** [comment]
Just an update in this - the SN75176AP works well!

This is the very basic schematic for the receiver:

![image](https://github.com/GDWoody/Pixel-Controllers/assets/71120697/4992c55f-5397-4b32-8cfb-edef93221b79)

Its actually the same as Scott Hanson used on his 'Single Receiver Out"

https://github.com/computergeek1507/PB_16/blob/master/Single_Receiver_Out/Single_Receiver_Out.pdf 

Thanks,

Joel.
